# Generated by Django 5.1.15 on 2026-10-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loading', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingoperator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loading_operator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadingsession',
            name='bay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='loading.loadingbay'),
        ),
        migrations.AddField(
            model_name='loadingsession',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_sessions', to='loading.driver'),
        ),
        migrations.AddField(
            model_name='loadingsession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='loading.loadingoperator'),
        ),
        migrations.AddField(
            model_name='loadingsession',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loading_session', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loadingsession',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_sessions', to='loading.truck'),
        ),
        migrations.AddField(
            model_name='weighbridgereading',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighbridge_readings', to='loading.loadingsession'),
        ),
    ]
