# Generated by Django 5.1.15 on 2026-10-02 16:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loading', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingsession',
            name='expected_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weighbridgereading',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighbridgereading',
            name='tolerance_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6),
        ),
    ]
