# Generated by Django 5.1.15 on 2026-10-02 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('shortage', 'Shortage'), ('damaged_bags', 'Damaged Bags'), ('quality_issue', 'Quality Issue'), ('wrong_product', 'Wrong Product')], max_length=20)),
                ('expected_bags', models.PositiveIntegerField()),
                ('received_bags', models.PositiveIntegerField()),
                ('shortage_bags', models.PositiveIntegerField()),
                ('shortage_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('credit_note_id', models.CharField(blank=True, max_length=50)),
                ('credit_note_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
