# Generated by Django 5.1.15 on 2026-10-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='dealers.dealer'),
        ),
    ]
