# Generated by Django 5.1.15 on 2026-10-02 16:26

import apps.claims.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='affected_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.claims.models.claim_evidence_upload_path),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='file_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('SHORTAGE', 'Shortage'), ('QUALITY_DAMAGE', 'Quality/Damage'), ('shortage', 'Shortage (Legacy)'), ('damaged_bags', 'Damaged Bags'), ('quality_issue', 'Quality Issue'), ('wrong_product', 'Wrong Product')], default='SHORTAGE', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='credit_note_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='claim',
            name='expected_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claim',
            name='received_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shortage_bags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claim',
            name='shortage_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('submitted', 'Submitted (Legacy)'), ('under_review', 'Under Review (Legacy)'), ('approved', 'Approved (Legacy)'), ('rejected', 'Rejected (Legacy)')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='claimevidence',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
