# Generated by Django 5.1.15 on 2026-10-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='assigned_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='distributors.distributor'),
        ),
    ]
