# Generated by Django 5.1.15 on 2026-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lr_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed')], default='IN_TRANSIT', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('seal_number', models.CharField(max_length=50)),
                ('qr_code_hash', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
