# Generated by Django 5.1.15 on 2026-10-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('loading', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='loading.driver'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass', to='orders.order'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='loading.truck'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='gate_pass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch', to='dispatch.gatepass'),
        ),
    ]
