# Generated by Django 5.1.15 on 2026-10-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_initial'),
        ('loading', '0003_loadingsession_expected_bags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='loading.driver'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='loading.truck'),
        ),
    ]
