# Generated by Django 5.1.15 on 2026-10-02 14:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('distributors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('truck_capacity', models.CharField(choices=[('20_MT', '20 MT (Max 400 Bags)'), ('25_MT', '25 MT (Max 500 Bags)')], max_length=10)),
                ('max_bags', models.PositiveIntegerField()),
                ('total_bags', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_weight_mt', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACED', 'Placed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('LOADING_QUEUED', 'Loading Queued'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('GATE_CLEARED', 'Gate Cleared'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CLAIM_PENDING', 'Claim Pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=25)),
                ('destination', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dealers.dealer')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='distributors.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags', models.PositiveIntegerField()),
                ('bag_weight_kg', models.PositiveIntegerField(default=50, editable=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_mt', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rate_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
